# Using SVM

In [42]:
from sklearn import svm

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [44]:
data=pd.read_csv('heart.data.txt', delimiter = ' ')
print(data)

      age  sex  chest_pain_type  resting_blood_pressure  serum_cholestoral  \
0    70.0  1.0              4.0                   130.0              322.0   
1    67.0  0.0              3.0                   115.0              564.0   
2    57.0  1.0              2.0                   124.0              261.0   
3    64.0  1.0              4.0                   128.0              263.0   
4    74.0  0.0              2.0                   120.0              269.0   
5    65.0  1.0              4.0                   120.0              177.0   
6    56.0  1.0              3.0                   130.0              256.0   
7    59.0  1.0              4.0                   110.0              239.0   
8    60.0  1.0              4.0                   140.0              293.0   
9    63.0  0.0              4.0                   150.0              407.0   
10   59.0  1.0              4.0                   135.0              234.0   
11   53.0  1.0              4.0                   142.0         

In [45]:
x=data.iloc[:,0:13]
print(x)

      age  sex  chest_pain_type  resting_blood_pressure  serum_cholestoral  \
0    70.0  1.0              4.0                   130.0              322.0   
1    67.0  0.0              3.0                   115.0              564.0   
2    57.0  1.0              2.0                   124.0              261.0   
3    64.0  1.0              4.0                   128.0              263.0   
4    74.0  0.0              2.0                   120.0              269.0   
5    65.0  1.0              4.0                   120.0              177.0   
6    56.0  1.0              3.0                   130.0              256.0   
7    59.0  1.0              4.0                   110.0              239.0   
8    60.0  1.0              4.0                   140.0              293.0   
9    63.0  0.0              4.0                   150.0              407.0   
10   59.0  1.0              4.0                   135.0              234.0   
11   53.0  1.0              4.0                   142.0         

In [53]:
y=data.iloc[:,13]
print(y)

0      2
1      1
2      2
3      1
4      1
5      1
6      2
7      2
8      2
9      2
10     1
11     1
12     1
13     2
14     1
15     1
16     2
17     2
18     1
19     1
20     2
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     2
29     1
      ..
240    2
241    1
242    1
243    2
244    1
245    2
246    2
247    1
248    2
249    2
250    2
251    1
252    2
253    1
254    1
255    1
256    1
257    2
258    2
259    1
260    1
261    2
262    2
263    1
264    2
265    1
266    1
267    1
268    1
269    2
Name: target, Length: 270, dtype: int64


In [54]:
from sklearn.model_selection import train_test_split

In [76]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [77]:
print(len(x_train))
print(len(x_test))

180
90


In [78]:
model=svm.SVC(kernel='linear')

In [79]:
model.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [80]:
y_predict=model.predict(x_test)
print(y_predict)

[2 1 1 1 1 2 2 1 1 1 1 2 2 2 1 1 2 1 2 1 2 1 2 1 2 2 2 2 1 1 1 1 2 1 1 2 2
 1 2 1 1 1 1 1 1 1 1 2 2 2 1 1 1 2 1 2 1 2 1 1 2 2 2 2 2 1 1 1 1 1 1 1 1 1
 1 1 1 2 2 1 1 2 1 2 2 2 2 1 2 1]


In [81]:
accuracy=model.score(x_test,y_test)
print(accuracy)

0.8111111111111111


# Using KNN 

In [82]:
from sklearn.neighbors import KNeighborsClassifier


In [114]:
knn=KNeighborsClassifier(n_neighbors=180)

In [84]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform')

In [119]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=180, p=2,
           weights='uniform')

In [86]:
knn.predict(x_test)

array([1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1,
       1, 1], dtype=int64)

In [120]:
accuracy_knn=knn.score(x_test,y_test)
print(accuracy_knn)


0.6


# Using Logistic Regression

In [121]:
from sklearn.linear_model import LogisticRegression

In [141]:
logreg=LogisticRegression(solver='liblinear',multi_class='ovr')

In [142]:
logreg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [143]:
logreg.predict(x_test)

array([2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1,
       2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1,
       2, 1], dtype=int64)

In [144]:
accuracy_logreg=logreg.score(x_test,y_test)
print(accuracy_logreg)

0.8777777777777778


# Using Decision Trees

In [145]:
from sklearn import tree

In [146]:
tr = tree.DecisionTreeClassifier()


In [147]:
tr.fit(x_test, y_test)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [148]:
tr.predict(x_test)

array([2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1,
       2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1,
       1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       2, 1], dtype=int64)

In [149]:
accuracy_tr=tr.score(x_test,y_test)
print(accuracy_tr)

1.0


# Using Neural Networks

In [150]:
from sklearn.neural_network import MLPClassifier

In [191]:
nn = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(50, 100), random_state=1)

In [192]:
nn.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [193]:
nn.predict(x_test)

array([2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1,
       1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1,
       2, 1], dtype=int64)

In [194]:
accuracy_nn=nn.score(x_test,y_test)
print(accuracy_nn)

0.8555555555555555
